### ISSUE TITLE
Application Form

### ISSUE THREAD

**Issue by jhilden** [colognerb/refugees#10]
To collect the information from potential participants it would be good to have a web form, where they can submit their information.

A Google Form that puts information into a Google Spreadsheet is probably a good solution.  Just like http://refugeesonrails.org does for laptop pickup:  https://docs.google.com/forms/d/17kbUGwkv5oi5OwUylki9Yfch3QsDBBZRbpEs8QXPo5A/viewform

These are the questions we should probably ask:
- English skil level
- German skill level
- other languages
- where are they from?  where do the live now?
- age
- IT/software experiecen
- short bio

If you have some time to create the form, please do it.

**Comment by sangyye** [comment]
I have created a form and added it to the webpage

**Comment by sangyye** [comment]
Application form is live and people are making registrations
