### ISSUE TITLE
Lunch

### ISSUE THREAD

**Issue by jhilden** [colognerb/refugees#15]
@tatjanala could you try to figure out how much lunch for ~30+ people would be, so we can try to find a sponsor for it.

Does anybody have good ideas who we could try to ask for sponsoring?

**Comment by erdnusskeks** [comment]
Denise, Martin Otten's wife, likes to bring something to eat. I think, that's a great idea! I could bring something, too. 
@tatjanala One thing to have in mind: I guess the food should be halal.

**Comment by tatjanala** [comment]
I could prepare something as well. For lunch we could have a "Falafel-Platte" from Hayati Imbiss for 30 people, it will cost around 300€. Does anyone know a sponsor for lunch?

**Comment by erdnusskeks** [comment]
I got the suggestion that Mealmates could be a nice sponsor (http://www.mealmates.de/). It's a start-up based in Cologne. But I guess they would provide their own food instead of paying for food made by Hayati Imbiss... But who knows! ; ) I will send them an e-mail and then we will see.

**Comment by jhilden** [comment]
@tatjanala could you take care of retrieving the money from the city ("städtische Förderung") via the Railslove bank account?   And could you also take care of organizing lunch catering for the next workshop?  Otherwise Elisa from Startplatz (Gihtub username??) might be able to help.

see also discussion here:  https://colognerb.slack.com/archives/refugees-on-rails/p1454061446000020

**Comment by jhilden** [comment]
@tatjanala what is the status here?  (FYI:  we will also need drinks)

**Comment by tatjanala** [comment]
@erdnusskeks  told me that I could spend 200€ for catering, will the amount be for both: drinks & food? I would suggest to order bagles & sandwiches from cafecafe. Is everyone fine with that?

**Comment by jhilden** [comment]
I think, it would be good if the amount would last for food & drink.  But it's probably a lot cheaper to just buy a couple of crates of water/softdrinks ourselves.

Cafecafe sounds great.  Let's say ~10-20 people for now and reconfirm with them, once we know the exact number.

**Comment by erdnusskeks** [comment]
There's a Lidl at Neumarkt Galerie, not far away from the Bib. We can buy some bottles of water and maybe apple juice. I would suggest to buy the small ones (0,5 l) so we won't need glasses.

**Comment by jhilden** [comment]
Sounds like a great plan.
