### ISSUE TITLE
Agenda: Saturday

### ISSUE THREAD

**Issue by jhilden** [colognerb/refugees#17]
This is the current agenda for Saturday

10:00 - 12:00
- workshop part I

12:00 - 13:00
- lunch

13:00 - 13:30
- inspriational talk by @salimhb 

13:30 - 15:30
- workshop part II

15:30 - 16:00 (+ open end)
- retrospective:  what did you like / not like?  (we will try to also have an anonymous feedback channel, for people that are too shy/polite, e.g. Google Forms)
- let's talk about next steps.  regular meetings?

Does anybody want to do any short inspirational talks?  Do we have somebody that could talk about his/her successfull refugee programming story?

**Comment by jhilden** [comment]
@salimhb would you be available to talk about your experience coming to Germany and succeeding in the programming business?

**Comment by salimhb** [comment]
Sure, when?
I'm planning to travel a weekend to cologne around the end of November or beginning December.

**Comment by stephanpavlovic** [comment]
Sounds perfect, we doing this on 27/28 of November @salimhb

**Comment by salimhb** [comment]
Great! Just had a Skype call with @jhilden to catch up with the agenda. I'll be joining for a talk and as a coach.
