### ISSUE TITLE
After the workshop

### ISSUE THREAD

**Issue by erdnusskeks** [colognerb/refugees#18]
Overview on what we can offer the participants after finishing the workshop:
- follow-up meetings (weekly? monthly?)
- availability via Slack
- Ruby usergroup colognerb (or other usergroups) to get/stay part of the community
- guest auditor at university ?!
- code schools on the internet --> what would you suggest?
- overview of conferences

--> anything else?!?

**Comment by erdnusskeks** [comment]
@koos In the coaches issue you suggested: "Another Idea would be to setup a special "How to meet the Cologne Tech Community" for refugees where all the other community events are listed etc." Have you already begun to collect the events?

**Comment by sangyye** [comment]
I would setup a [dokuwiki](https://www.dokuwiki.org/dokuwiki) and host it for maintaining a knowledge base for all refugee information on the net. We only need a good domain name for that ;)

**Comment by erdnusskeks** [comment]
@tatjanala Do you know if the laptops from the Webmontag guy can be used by the refugees after the workshop at the office/institution where they have to be brought back on Monday? If we don't have enough laptops to give them to all the participants they would still have an opportunity to continue learning by using these computers. Or are they usually used for everyday training courses or something like that? It only makes sense if the computers are (more or less) free accessible for the refugees.

**Comment by tatjanala** [comment]
I don't think the laptops can be used by the participants after the workshop. The laptops are for training purposes only and always shipped to different places/workshops in NRW....

**Comment by erdnusskeks** [comment]
@tatjanala Alright!

**Comment by erdnusskeks** [comment]
Probably, we won't have enough laptops for all the participants to take with them after the workshop. So,  does anyone know where the refugees can go to for continuing to learn/code? Where can they find free spaces with computers? Of course, Ruby and Rails have to be installed on the devices. Any ideas?

**Comment by sangyye** [comment]
http://refugee-guides.soup.io/ seems to be a good link collection.

**Comment by erdnusskeks** [comment]
@sangyye thanks for the link. Sounds good. But I thought about some kind of ROOM where the refugees can use computers. Are there any open spaces with computer for free use in or around Cologne?

**Comment by sangyye** [comment]
I could maybe organize some Desktops (only the Desktop, without Screens, Mouse and Keyboard), if we find some room I could set up a little Computer Lab for the Refugees.

**Comment by jhilden** [comment]
@sangyye that sounds like a nice project idea.  Especially if some of the refugees would particpate in setting up and running this computer lab.  Check out this Chaosradio podcast episode for details on that: http://chaosradio.ccc.de/cr216.html

But I guess the biggest Problem here would be finding a room.  It could be that somebody from the City is coming, they might be able to help with that (cc @koos )

**Comment by erdnusskeks** [comment]
I heard of this project: refugeesemancipation.com It's about empowering refugees to improve their situation e.g. by building up internetcafes.

**Comment by z1337** [comment]
For those participants who'd like to continue in learning some basic programming here some links.

Some general tutorials (different languages available): 
http://code.org/learn
http://www.tutorialspoint.com/java/index.htm

Good basic Java intro:
https://netbeans.org/kb/articles/learn-java.html

Ruby:
http://tryruby.org

Free books on different programming languages for downloads (some rather exotic):
https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md

Currently there is an online course for python running, maybe it is still possible to join. It is target for kids and is in german:
https://open.hpi.de/courses/pythonjunior2015

**Comment by z1337** [comment]
Another thing we might collect are companies/oraganisations that might offer internships, best grouped by technolgies desired:

For C#/.net I found out
cleverbridge.com
controlexpert.com

**Comment by jhilden** [comment]
thanks for all the resources @z1337 

until we have something better, I started putting all that information into the wiki on this github repository.  please add additional information there and leave useful comments on existing resources, so that this is something really usable for the refugees:
https://github.com/colognerb/refugees/wiki

**Comment by erdnusskeks** [comment]
I received an e-mail concerning financial support for projects. Deadline: 11.12. (!)
Might be interesting for us - or what do you think?

Von: Kölner Freiwilligen Agentur [mailto:mentoren@koeln-freiwillig.de] 
Gesendet: Mittwoch, 9. Dezember 2015 11:47
Betreff: WG: Projektunterstützung: Den Mantel teilen vor Ort

Liebe Engagierte,

auf Bitte des Amt für Presse- und Öffentlichkeitsarbeit der Stadt Köln leite ich untenstehende Mail, die uns gerade erreichte, gerne weiter.

Beantragt werden kann Unterstützung für „insbesondere Maßnahmen in den Bereichen der kulturellen Aktivitäten“ in Höhe von max. 1000€. Bitte beachten: Rückmeldefrist ist der 11.12.2015!

---

Sehr geehrte Damen und Herren,

Ihre Willkommensinitiative trägt maßgeblich mit dazu bei, die konkreten Lebensbedingungen der Flüchtlinge in unserer Stadt zu verbessern. Durch Ihre Arbeit für und mit den Flüchtlingen haben Sie nicht nur in den vergangenen Monaten Großartiges geleistet, sondern Sie werden aufgrund ihrer Arbeit „vor Ort“ am besten mit beurteilen können, wo weitere konkrete Handlungsbedarfe im Sinne einer hilfreichen Unterstützung bestehen und mit welchen Mitteln und Maßnahmen diese in geeigneter Weise zu erfüllen sind.

Aus diesem Grunde dürfen wir uns mit der Initiative „Den Mantel teilen“ im Verbund mit dem Kölner Flüchtlingsrat e. V. sowie der Stadt Köln, vertreten durch die Stabsstelle Events, direkt an Sie wenden und Ihnen unsere Unterstützung anbieten. Nachdem wir uns in den vergangenen Jahren auf die Durchführung von Kundgebungen konzentriert haben, bei denen es vor allem darum ging, eine Öffentlichkeit für die Probleme und Unterstützungsbedarfe zu schaffen, haben wir uns für dieses Jahr entschieden, die uns zur Verfügung stehenden finanziellen Mittel für konkrete Hilfen bereitzustellen. Und auch wenn diese Mittel sicherlich eher einen bescheiden Umfang ausweisen, so erscheinen Sie uns jedoch ausreichend, um zumindest die ein oder andere sinnvolle Maßnahme, für die eben bei Ihren Initiativen möglicherweise kein Budget zur Verfügung steht, verwirklichen zu können.

Wir denken dabei insbesondere an Maßnahmen in den Bereichen der kulturellen Aktivitäten, sei es etwa der Besuch von Veranstaltungen oder kulturellen Einrichtungen, sei es die Durchführung eines eigenen Festes oder seien es auch länger andauernde Maßnahmen, wie das Angebot von Musikkursen o. ä.. Bei der Vernetzung zu kulturellen Einrichtungen, Trägern oder Künstlern helfen wir gerne.  Ebenso sind aber auch Aktivitäten in der Freizeitgestaltung wie z. B. Schwimmbadbesuche, Sportangebote (inkl. der Anschaffung erforderlicher Bekleidung oder sonstiger Materialien und Ausstattung) möglich.

Sollten Sie hierfür im Rahmen Ihrer Arbeit einen Bedarf sehen, für dessen Umsetzung Sie zusätzliche finanzielle Unterstützung benötigen, dann lassen Sie es uns doch bitte wissen. Um die vorhandenen Mittel möglichst breit zu streuen, stellen wir uns vor, dass sich Ihre Wünsche jeweils auf einen Unterstützungsbedarf von bis zu 1.000 € beschränken.  

Anstelle eines bürokratisch aufwändigen Antragsverfahrens können Sie uns Ihren Unterstützungswunsch mit einer kurzen Beschreibung der Maßnahme und den dafür erforderlichen Mitteln formlos per E-Mail oder Fax zukommen lassen. Verwenden Sie bitte dazu die E-Mail-Adresse bzw. Faxnummer der Stabsstelle Events:
E-Mail: stabsstelle-events@stadt-koeln.de bzw. Fax-Nr. 0221-221-23322.

Die Stabsstelle steht Ihnen auch für weitere Fragen zum Verfahren unter der Telefonnummer 0221-221-26018 gerne zur Verfügung.

Damit wir die Unterstützung auch zeitnah umsetzen können, wären wir für eine Rückmeldung bis zum 11.12.2015 dankbar.

**Comment by jhilden** [comment]
Sounds generally interesting and the effort involved seems to be relatively low.

The question would be "what is the concrete thing that we could use funding for?" except for catering I can't really think of anything.  Anybody have a better idea?

Also, a question is if we would have to be a "Verein" or some organisation in order to receive the money.
