### ISSUE TITLE
Create stickers for the laptops

### ISSUE THREAD

**Issue by jhilden** [colognerb/refugees#20]
As @erdnusskeks suggested today it would be nice to put the name & contact of the donor onto the laptops, so that the refugees can contact them if they want to and so the donors get some recognition.

Maybe is what we could put on there?

```
This laptop is property of Refugeesonrails.org

It was kindly donated by:
Email:

It has been given to:
```

Anybody want to create a template document for that?

@westonhankins are you doing anything in this direction?

**Comment by westonhankins** [comment]
We keep an excel list of donors for those that gave us details about them and that's it. There is no way to trace a laptop back to it's original owner. We do have a small circular sticker that has our refugees on rails logo that we paste on them.

[150903_Sticker_ROR_.pdf](https://github.com/colognerb/refugees/files/33816/150903_Sticker_ROR_.pdf)

**Comment by westonhankins** [comment]
[150903_Sticker_ROR_.pdf](https://github.com/colognerb/refugees/files/33814/150903_Sticker_ROR_.pdf)

**Comment by jhilden** [comment]
@westonhankins sounds good, thanks.  could you provide us with a couple of stickers?  Maybe @oezlemburan could take them along from Berlin?

**Comment by westonhankins** [comment]
Hi @jhilden! I just shared a Google Drive folder with promotional material you can use.

**Comment by jhilden** [comment]
thanks @westonhankins 

@tatjanala could you maybe take care of printing out some stickers and maybe a poster for the front door?

**Comment by oezlemburan** [comment]
Hi All,

Sorry for my late reply.
I'm bringing 14 stickers (that's all we had left) and a bunch of flyers
along. Unfortunately, we needed our roll-up in Berlin for several events so
I could not bring that one with me.

Best,
Oezlem

_________________________// Oezlem BuranDirector Public Relations & Public
Affairs Refugees on RailsSkype ID:
oezlemburanE-mail: oezlem@refugeesonrails.org
oezlem@refugeesonrails.orgMobile: +49 (0)1 577 344 39
08www.refugeesonrails.org http://www.refugeesonrails.org/_
