### ISSUE TITLE
E-mail for the participants

### ISSUE THREAD

**Issue by erdnusskeks** [colognerb/refugees#21]
Here is my draft: 

Dear participant,

thank you for applying to our workshop!
We are excited to meet you and get to know you. : )

In this e-mail you will get all the information you need.

The workshop will happen at the coworking space Cowoco (An der Bottmühle 5, 50678 Köln, coworkingcologne.de/space). It starts on Friday November 27th at 6 o'clock / 6pm with a warm-up and a short round of introductions. Then we will tell you about the agenda. On Saturday (November 28th), we will begin to learn Ruby on Rails at 10 o'clock / 10am. Laptops will be provided by us. 
The essential thing about the workshop is that you will learn everything by yourself. The coaches will help you if you get stuck. After the workshop you should be able to understand Ruby on Rails. With a little practice you will be able to code simple applications in a very short time. Ruby on Rails is quite easy to understand, and it is fun to work with RoR!

We don't have a big budget. So it would be nice if anyone could bring some food. Just some fingerfood, sandwiches, cake, fruits, or something like that. We have a google doc to write down the food you'd like to share with us all. 
--- LINK!!! ---
Thank you!

The workshop is not yet full up. So tell everyone about it! We are looking forward to receiving some more applications!

On the other hand, please tell us if you can't afford to participate although you applied for the workshop (because of other appointments, illness, etc.).
You can write an e-mail to: refugeesonrails@gmail.com

But hopefully we are looking forward to meeting you all next week, healthy and motivated!

All the best
your Refugees on Rails Cologne organisation team

---

Was fehlt:
- der Google-Doc-Link für die Essensübersicht --> auf der Webseite steht übrigens noch, dass wir fürs Essen sorgen!
- ein Ausblick auf das, was nach dem Workshop kommt (Meet-ups, Slack-Channel etc.)

**Comment by jhilden** [comment]
sounds great.  thanks.  could you maybe put the text into some tool like Google Docs or hackpad, so others can easily makes changes/comments?

**Comment by erdnusskeks** [comment]
Here we go: https://hackpad.com/E-mail-for-participants-mEtk68EE6Lo ; )
I hope it works..

**Comment by erdnusskeks** [comment]
E-Mail ist raus (ohne den Teil übers Essen), aber eine Mailadresse (die von Khalid) funktioniert leider  nicht.
