### ISSUE TITLE
One more e-mail for the participants

### ISSUE THREAD

**Issue by erdnusskeks** [colognerb/refugees#22]
One more e-mail for the participants, containing:
- info about food
- maybe info about number of participants, noch freie Plätze etc.

**Comment by jhilden** [comment]
Very good point.  Anybody else have any thoughts on what should be included in this email?  Could you create a draft @erdnusskeks?

We should also ask them in the email if they have any open questions about the workshop.

**Comment by erdnusskeks** [comment]
- explain how to get to Cowoco
- maybe hint at agenda on website
