### ISSUE TITLE
First meeting

### ISSUE THREAD

**Issue by jhilden** [colognerb/refugees#3]
Our first meeting will be on Thursday September 24,  19:00,  at Coworking Cologne http://coworkingcologne.de/space/

**Comment by jhilden** [comment]
I also added the meeting here:  http://www.colognerb.de/events/refugees-meetup

**Comment by jhilden** [comment]
Address:

Coworking Cologne 
An der Bottmühle 5 
50678 Köln

**Comment by jhilden** [comment]
Looks like a number of interested people will be at the AWS Meetup at GrandCentrix tomorrow (Thursday) evening (http://www.meetup.com/de/aws-cologne/events/224141069/).  For example @larsvegas

The only definitv participatns that I know of are @erdnusskeks and @sangyye:  What would you think about changing our location to GrandCentrix?  - for me it would definitely be closer to home ;)  Would be nice if you could give notice until tomorrow (Thursday) 12:00

Of course the precondition would be that this is OK for GrandCentrix.  @larsvegas could you check that?  Or tell me who I could ask?

People who want to help, but won't be able to attend are @koos and @tatjanala.  For them and other people in the same situation, please add yourself to the wiki page https://github.com/colognerb/refugees/wiki/List-of-potential-organizers-and-helpers, so we know how many we are and who wants to do what.

**Comment by erdnusskeks** [comment]
Hi Jakob,

changing the location is no problem.
But I would be very happy if we could start with the refugees meeting and
after that continue with the AWS meet-up - because of little Nora who will
join us. : ) Might that be possible?

Kind regards
Denise
Am 23.09.2015 20:10 schrieb "Jakob Hilden" notifications@github.com:

**Comment by jhilden** [comment]
I could imagine starting early (maybe 18:15/18:30) and doing a short 5 minute pitch of the project at the beginning of the AWS meetup (if that is OK @larsvegas?).

If you want we can continue with the refugess topic in parallel to the AWS meetup, if there is some sort of second room and little Nora is OK with it ;)
And I would hang around until after the meetup if there are more people that would be interested in helping.

**Comment by sangyye** [comment]
Hi @jhilden,

I also have no problem with the location change, not sure if I can make it on time. But I will try it. Don't know there was an AWS Meetup, Maybe also interesting. Thanks for notifying.

**Comment by larsvegas** [comment]
Hey @jhilden,
@erdnusskeks,
@sangyye!

No problem that you do a intro talk. But the Meeting starts at 1900. We won't start with talks before 1930. 
See you all tomorrow! :)

**Comment by larsvegas** [comment]
Ah, please RSVP @ http://www.meetup.com/de/aws-cologne/events/224141069/ for statistical, drink and food reasons :)

**Comment by zakx** [comment]
Hey there, of course y'all are welcome @grandcentrix! Not sure if we can amend the food order on short notice, but if there's not enough for everybody we can still order some pizza etc.
See you tomorrow!

**Comment by erdnusskeks** [comment]
Great! We are looking forward to seeing you all today (19:00) @
Grandcentrix!
Am 23.09.2015 23:39 schrieb "zakx" notifications@github.com:

**Comment by jhilden** [comment]
Thanks @zakx   and we are not coming for the food, so don't worry about that ;)

See you at 19:00, that will give us 30 minutes before the meetup.

Changed accordingly:
http://www.colognerb.de/events/refugees-meetup
https://twitter.com/colognerb/status/646966826224734208

**Comment by jhilden** [comment]
Here are the notes from todays meeting:

---

Basisziel:
- mögichst schnell mit kleinen Mitteln ein erstes Event mit Flüchtligen organisieren
- das ist erstmal nur als Pilotveranstaltung gedacht.  Danach kann man weiterguckn, was funktioniert, was am meisten Sinn macht, wie man am besten Helfen kann

Wann:  Ende November (Fr/Sa):  21./22. oder 27./28.
Was:  Workshop angelehnt an Refugeesonrails

Wer:
- 20 Teilnehmern
- 10 Coaches

Womit:
- 20 Laptops die wir versuchen wollen einzusammeln 

Wo:
- Cowoco  (alternativvorschlag: C4)

Was sind geeignete Teilnehmern?
- Basis Englischkenntnisse
- Fortgeschrittene Deutsch oder Englischkenntnisse (sofern keine Übersetzer)
- IT interessiert
- Alter egal
- ansässig im Raum Köln

Wir brauchen einen Fragebogen für die Bewerbung:
- Englischkenntnisse
- Deutschkenntnisse
- weitere Sprachkenntisse
- Wohnort/Anfahrt
- Alter
- IT Erfahrung
- Kurzbio

Am besten wahrscheinlich als Google Form 

Wie erreichen wir Teilnehmer?
- Flyer
- rumtelefonieren
  siehe:  https://github.com/colognerb/refugees/issues/2

Erfahrung sammeln von anderen Initiativen:  z.B. Computerkurse

Lehrmaterial:
- angelehnt an Railsgirls (in welchen Sprachen verfügbar?)

Coaching:
- Code of conduct der OpenTechSchool  (@sangyee hast du einen Link?)

TODOs:
- gmail adresse einrichten
- Slack channel (Christian)  https://github.com/colognerb/refugees/issues/7
- Initiativen kontaktieren (Sebastian)
- Coaches (Jakob) https://github.com/colognerb/refugees/issues/5
- Laptops (Christian)  https://github.com/colognerb/refugees/issues/6

Nächstes Treffen:
nächste Woche Donnerstag 1. Oktober, 19:00 im Cowoco   https://github.com/colognerb/refugees/issues/8

**Comment by sangyye** [comment]
@jhilden I found the coaching slides https://opentechschool.github.io/slides/presentations/coaching/ I think we should meet up a few days before with all coaches and show the slides and talk a little about our goal.

**Comment by sangyye** [comment]
For the material, it seems good to start with http://guides.railsgirls.com/?
