### ISSUE TITLE
Create a chat channel (Slack etc.)

### ISSUE THREAD

**Issue by jhilden** [colognerb/refugees#7]

**Comment by sangyye** [comment]
I have created a slack channel on https://colognerb.slack.com/ We only have to set up the automatically invite system like https://github.com/rauchg/slackin, for the time being you can request an invite and i will take care of adding you.

**Comment by jhilden** [comment]
I couldn't find out how to request an invite.  You have any hints for me?

**Comment by sangyye** [comment]
@jhilden sorry, you have to send me your email adress and i will send you an invite. I have to set up the automatically invite system this weekend

**Comment by sangyye** [comment]
Done. You can join our slack channel on http://colognerb.sangyye.net/
